# 📦 Base de datos PostgreSQL (Neon.tech)
#spring.datasource.url=jdbc:postgresql://ep-patient-surf-ahxbnqp3-pooler.c-3.us-east-1.aws.neon.tech:5432/loopi?sslmode=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_tjAY2VBNl4bD
#spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://localhost:5432/loopi
spring.datasource.username=loopi
spring.datasource.password=loopi

# ⚙️ JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# 🔄 Pool de conexiones (opcional, mejora el rendimiento)
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# 🌐 Puerto del servidor
server.port=8081

# 📧 Configuración de correo SMTP (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=loopi5075@gmail.com
spring.mail.password=xugl thvg heyn mdiu
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
