name: Angular CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Entrar a carpeta frontend
      run: cd frontend

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar dependencias
      run: npm install
      working-directory: frontend

    - name: Ejecutar pruebas con ng test
      run: npx ng test --watch=false --browsers=ChromeHeadless
      working-directory: frontend
